# Generated by Django 3.2.5 on 2021-09-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1987, max_length=200),
            preserve_default=False,
        ),
    ]
