# Generated by Django 3.2.5 on 2021-09-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
