# Generated by Django 3.2.8 on 2021-10-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feeds',
            field=models.CharField(default=1987, max_length=1000),
            preserve_default=False,
        ),
    ]
