# Generated by Django 3.2.5 on 2021-08-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210729_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=1987, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=1987, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=1987, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.author'),
        ),
    ]
