# Generated by Django 3.2.5 on 2021-08-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210831_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='blog',
            new_name='author',
        ),
    ]
