# Generated by Django 3.2.6 on 2021-09-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lurl', models.CharField(max_length=999)),
                ('surl', models.CharField(max_length=30)),
            ],
        ),
    ]
