# Generated by Django 3.2.5 on 2021-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_app', '0002_short_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='slug',
            field=models.SlugField(blank=True, max_length=8, null=True),
        ),
    ]
