# Generated by Django 3.2.7 on 2021-09-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort_app', '0004_auto_20210910_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short',
            name='id',
        ),
        migrations.AlterField(
            model_name='short',
            name='code',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
