# Generated by Django 3.2.7 on 2021-09-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
