# Generated by Django 3.2.7 on 2021-09-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210925_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
