# Generated by Django 3.2.8 on 2021-10-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0007_alter_feeds_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='AvailableFeeds',
            field=models.ManyToManyField(blank=True, to='info_app.FeedName'),
        ),
    ]
