# Generated by Django 3.2.8 on 2021-10-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_feeds'),
        ('info_app', '0008_alter_usersubscriptions_availablefeeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='subscriber',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
