# Generated by Django 3.2.8 on 2021-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timesCorrect', models.SmallIntegerField(default=0)),
                ('timesIncorrect', models.SmallIntegerField(default=0)),
                ('dateCorrect', models.DateTimeField(auto_now=True)),
                ('imgURL', models.CharField(max_length=500)),
                ('bin', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
