# Generated by Django 3.2.6 on 2021-09-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('date_create', models.DateTimeField()),
                ('date_complete', models.DateTimeField()),
                ('flag_complete', models.BooleanField()),
            ],
        ),
    ]
