# Generated by Django 3.2.5 on 2021-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('photographer', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('raw', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
                ('small', models.CharField(max_length=200)),
                ('regular', models.CharField(max_length=200)),
                ('download', models.CharField(max_length=200)),
            ],
        ),
    ]
