# Generated by Django 3.2.7 on 2021-09-18 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('thumb', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('photographer', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_description', models.CharField(blank=True, max_length=200, null=True)),
                ('raw', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
                ('small', models.CharField(max_length=200)),
                ('regular', models.CharField(max_length=200)),
                ('download', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='splash_app.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='item_order', to='splash_app.Item')),
                ('profile', models.ManyToManyField(to='splash_app.ProfileModel')),
            ],
        ),
    ]
