# Generated by Django 3.2.7 on 2021-09-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_ordered',
            new_name='date_added',
        ),
    ]
