# Generated by Django 3.2.7 on 2021-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_app', '0002_auto_20210916_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='alt_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
