# Generated by Django 3.2.7 on 2021-09-17 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splash_app', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
    ]
