# Generated by Django 3.2.7 on 2021-11-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Diary',
        ),
    ]
