# Generated by Django 3.2.7 on 2021-09-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_checkout_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='library_app.profile'),
        ),
    ]
