# Generated by Django 3.1.5 on 2021-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(blank=True, max_length=500)),
                ('thumb', models.CharField(blank=True, max_length=500)),
                ('download', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='getImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(blank=True, max_length=500)),
                ('thumb', models.CharField(blank=True, max_length=500)),
                ('download', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
