# Generated by Django 3.2.5 on 2021-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getimages',
            name='my_image',
            field=models.ImageField(default=1987, upload_to=''),
            preserve_default=False,
        ),
    ]
