# Generated by Django 3.2.5 on 2021-09-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash_app', '0002_getimages_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimages',
            name='my_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
